/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubmitQueryRequest
 */
export interface SubmitQueryRequest {
    /**
     * 
     * @type {string}
     * @memberof SubmitQueryRequest
     */
    queryText: string;
    /**
     * 
     * @type {string}
     * @memberof SubmitQueryRequest
     */
    userId?: string;
}

/**
 * Check if a given object implements the SubmitQueryRequest interface.
 */
export function instanceOfSubmitQueryRequest(value: object): value is SubmitQueryRequest {
    if (!('queryText' in value) || value['queryText'] === undefined) return false;
    return true;
}

export function SubmitQueryRequestFromJSON(json: any): SubmitQueryRequest {
    return SubmitQueryRequestFromJSONTyped(json, false);
}

export function SubmitQueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitQueryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'queryText': json['query_text'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function SubmitQueryRequestToJSON(value?: SubmitQueryRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'query_text': value['queryText'],
        'user_id': value['userId'],
    };
}

